--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JavierLeon9966/ProperDuels
build-by-default: true
branches:
- master
projects:
  ProperDuels:
    libs:
      - src: ACM-PocketMine-MP/Commando/Commando # Temporary until the original updates
        version: ^3.2.0
        branch: PM5
      - src: poggit/libasynql/libasynql
        branch: "pm5"
        version: ^4.1.0
...
