<?php

/*
 * Auto-generated by libasynql-fx
 * Created from stmt.sql, stmt.sql
 */

declare(strict_types=1);

namespace JavierLeon9966\ProperDuels;

use Generator;
use JavierLeon9966\ProperDuels\libs\_3b83941958c6d0cd\poggit\libasynql\DataConnector;
use JavierLeon9966\ProperDuels\libs\_3b83941958c6d0cd\SOFe\AwaitGenerator\Await;

final class RawQueries{
	public function __construct(private DataConnector $conn) {}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:279
	 * - ./resources/sqlite/stmt.sql:139
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function checkForMigrationArenas() : Generator {
		$this->conn->executeSelect("properduels.check_for_migration.arenas", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:274
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function checkForMigrationKits() : Generator {
		$this->conn->executeSelect("properduels.check_for_migration.kits", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:229
	 * - ./resources/sqlite/stmt.sql:91
	 * @param string $name
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function deleteArena(string $name, ) : Generator {
		$this->conn->executeChange("properduels.delete.arena", ["name" => $name, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:224
	 * - ./resources/sqlite/stmt.sql:86
	 * @param string $name
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function deleteKit(string $name, ) : Generator {
		$this->conn->executeChange("properduels.delete.kit", ["name" => $name, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:241
	 * - ./resources/sqlite/stmt.sql:103
	 * @param string $name
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function getArena(string $name, ) : Generator {
		$this->conn->executeSelect("properduels.get.arena", ["name" => $name, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:236
	 * - ./resources/sqlite/stmt.sql:98
	 * @param string $name
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function getKit(string $name, ) : Generator {
		$this->conn->executeSelect("properduels.get.kit", ["name" => $name, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:248
	 * - ./resources/sqlite/stmt.sql:110
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function getRandomArena() : Generator {
		$this->conn->executeSelect("properduels.get_random.arena", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:253
	 * - ./resources/sqlite/stmt.sql:115
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function getRandomKit() : Generator {
		$this->conn->executeSelect("properduels.get_random.kit", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:167
	 * - ./resources/sqlite/stmt.sql:29
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function initArenas() : Generator {
		$this->conn->executeChange("properduels.init.arenas", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/sqlite/stmt.sql:6
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function initForeignKeys() : Generator {
		$this->conn->executeChange("properduels.init.foreign_keys", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:58
	 * - ./resources/sqlite/stmt.sql:14
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function initKits() : Generator {
		$this->conn->executeChange("properduels.init.kits", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:267
	 * - ./resources/sqlite/stmt.sql:129
	 * @param int $offset
	 * @param int $limit
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function listArenas(int $offset, int $limit, ) : Generator {
		$this->conn->executeSelect("properduels.list.arenas", ["offset" => $offset, "limit" => $limit, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:261
	 * - ./resources/sqlite/stmt.sql:123
	 * @param int $offset
	 * @param int $limit
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function listKits(int $offset, int $limit, ) : Generator {
		$this->conn->executeSelect("properduels.list.kits", ["offset" => $offset, "limit" => $limit, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/sqlite/stmt.sql:37
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function loadArenas() : Generator {
		$this->conn->executeSelect("properduels.load.arenas", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/sqlite/stmt.sql:34
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function loadKits() : Generator {
		$this->conn->executeSelect("properduels.load.kits", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:175
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function loadOldArenas() : Generator {
		$this->conn->executeSelect("properduels.load_old.arenas", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:172
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function loadOldKits() : Generator {
		$this->conn->executeSelect("properduels.load_old.kits", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/sqlite/stmt.sql:175
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function migrateArenas() : Generator {
		$this->conn->executeChange("properduels.migrate.arenas", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:217
	 * - ./resources/sqlite/stmt.sql:79
	 * @param string $name
	 * @param string $levelName
	 * @param float $firstSpawnPosX
	 * @param float $firstSpawnPosY
	 * @param float $firstSpawnPosZ
	 * @param float $secondSpawnPosX
	 * @param float $secondSpawnPosY
	 * @param float $secondSpawnPosZ
	 * @param ?string $kit
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function registerArena(string $name, string $levelName, float $firstSpawnPosX, float $firstSpawnPosY, float $firstSpawnPosZ, float $secondSpawnPosX, float $secondSpawnPosY, float $secondSpawnPosZ, ?string $kit, ) : Generator {
		$this->conn->executeInsert("properduels.register.arena", ["name" => $name, "levelName" => $levelName, "firstSpawnPosX" => $firstSpawnPosX, "firstSpawnPosY" => $firstSpawnPosY, "firstSpawnPosZ" => $firstSpawnPosZ, "secondSpawnPosX" => $secondSpawnPosX, "secondSpawnPosY" => $secondSpawnPosY, "secondSpawnPosZ" => $secondSpawnPosZ, "kit" => $kit, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:184
	 * - ./resources/sqlite/stmt.sql:46
	 * @param string $name
	 * @param string $armor
	 * @param string $inventory
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function registerKit(string $name, string $armor, string $inventory, ) : Generator {
		$this->conn->executeInsert("properduels.register.kit", ["name" => $name, "armor" => $armor, "inventory" => $inventory, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:292
	 * - ./resources/sqlite/stmt.sql:188
	 * @param string $name
	 * @param string $armor
	 * @param string $inventory
	 * @param ?string $newName
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function updateKit(string $name, string $armor, string $inventory, ?string $newName, ) : Generator {
		$this->conn->executeChange("properduels.update.kit", ["name" => $name, "armor" => $armor, "inventory" => $inventory, "newName" => $newName, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}
}