<?php

/*
 * Auto-generated by libasynql-fx
 * Created from stmt.sql, stmt.sql
 */

declare(strict_types=1);

namespace JavierLeon9966\ProperDuels;

use Generator;
use JavierLeon9966\ProperDuels\libs\_ded2d3c19935ef44\poggit\libasynql\DataConnector;
use JavierLeon9966\ProperDuels\libs\_ded2d3c19935ef44\SOFe\AwaitGenerator\Await;

final class RawQueries{
	public function __construct(private DataConnector $conn) {}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:294
	 * - ./resources/sqlite/stmt.sql:150
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function checkForMigrationArenas() : Generator {
		$this->conn->executeSelect("properduels.check_for_migration.arenas", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:289
	 * - ./resources/sqlite/stmt.sql:142
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function checkForMigrationKits() : Generator {
		$this->conn->executeSelect("properduels.check_for_migration.kits", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:242
	 * - ./resources/sqlite/stmt.sql:92
	 * @param string $name
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function deleteArena(string $name, ) : Generator {
		$this->conn->executeChange("properduels.delete.arena", ["name" => $name, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:237
	 * - ./resources/sqlite/stmt.sql:87
	 * @param string $name
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function deleteKit(string $name, ) : Generator {
		$this->conn->executeChange("properduels.delete.kit", ["name" => $name, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:255
	 * - ./resources/sqlite/stmt.sql:105
	 * @param string $name
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function getArena(string $name, ) : Generator {
		$this->conn->executeSelect("properduels.get.arena", ["name" => $name, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:250
	 * - ./resources/sqlite/stmt.sql:100
	 * @param string $name
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function getKit(string $name, ) : Generator {
		$this->conn->executeSelect("properduels.get.kit", ["name" => $name, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:262
	 * - ./resources/sqlite/stmt.sql:112
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function getRandomArena() : Generator {
		$this->conn->executeSelect("properduels.get_random.arena", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:268
	 * - ./resources/sqlite/stmt.sql:118
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function getRandomKit() : Generator {
		$this->conn->executeSelect("properduels.get_random.kit", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:180
	 * - ./resources/sqlite/stmt.sql:30
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function initArenas() : Generator {
		$this->conn->executeChange("properduels.init.arenas", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/sqlite/stmt.sql:6
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function initForeignKeys() : Generator {
		$this->conn->executeChange("properduels.init.foreign_keys", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:71
	 * - ./resources/sqlite/stmt.sql:15
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function initKits() : Generator {
		$this->conn->executeChange("properduels.init.kits", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:282
	 * - ./resources/sqlite/stmt.sql:132
	 * @param int $offset
	 * @param int $limit
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function listArenas(int $offset, int $limit, ) : Generator {
		$this->conn->executeSelect("properduels.list.arenas", ["offset" => $offset, "limit" => $limit, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:276
	 * - ./resources/sqlite/stmt.sql:126
	 * @param int $offset
	 * @param int $limit
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function listKits(int $offset, int $limit, ) : Generator {
		$this->conn->executeSelect("properduels.list.kits", ["offset" => $offset, "limit" => $limit, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/sqlite/stmt.sql:38
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function loadArenas() : Generator {
		$this->conn->executeSelect("properduels.load.arenas", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/sqlite/stmt.sql:35
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function loadKits() : Generator {
		$this->conn->executeSelect("properduels.load.kits", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:188
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function loadOldArenas() : Generator {
		$this->conn->executeSelect("properduels.load_old.arenas", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:185
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
	 */
	public function loadOldKits() : Generator {
		$this->conn->executeSelect("properduels.load_old.kits", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/sqlite/stmt.sql:190
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function migrateArenas() : Generator {
		$this->conn->executeChange("properduels.migrate.arenas", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/sqlite/stmt.sql:156
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function migrateKits() : Generator {
		$this->conn->executeChange("properduels.migrate.kits", [], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:230
	 * - ./resources/sqlite/stmt.sql:80
	 * @param string $name
	 * @param string $levelName
	 * @param float $firstSpawnPosX
	 * @param float $firstSpawnPosY
	 * @param float $firstSpawnPosZ
	 * @param float $secondSpawnPosX
	 * @param float $secondSpawnPosY
	 * @param float $secondSpawnPosZ
	 * @param ?string $kit
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function registerArena(string $name, string $levelName, float $firstSpawnPosX, float $firstSpawnPosY, float $firstSpawnPosZ, float $secondSpawnPosX, float $secondSpawnPosY, float $secondSpawnPosZ, ?string $kit, ) : Generator {
		$this->conn->executeInsert("properduels.register.arena", ["name" => $name, "levelName" => $levelName, "firstSpawnPosX" => $firstSpawnPosX, "firstSpawnPosY" => $firstSpawnPosY, "firstSpawnPosZ" => $firstSpawnPosZ, "secondSpawnPosX" => $secondSpawnPosX, "secondSpawnPosY" => $secondSpawnPosY, "secondSpawnPosZ" => $secondSpawnPosZ, "kit" => $kit, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:197
	 * - ./resources/sqlite/stmt.sql:47
	 * @param string $name
	 * @param string $armor
	 * @param string $inventory
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function registerKit(string $name, string $armor, string $inventory, ) : Generator {
		$this->conn->executeInsert("properduels.register.kit", ["name" => $name, "armor" => $armor, "inventory" => $inventory, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:316
	 * - ./resources/sqlite/stmt.sql:212
	 * @param string $name
	 * @param bool $enabled
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function setEnabledKit(string $name, bool $enabled, ) : Generator {
		$this->conn->executeChange("properduels.set_enabled.kit", ["name" => $name, "enabled" => $enabled, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}

	/**
	 * <h4>Declared in:</h4>
	 * - ./resources/mysql/stmt.sql:307
	 * - ./resources/sqlite/stmt.sql:203
	 * @param string $name
	 * @param string $armor
	 * @param string $inventory
	 * @param string $newName
	 * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
	 */
	public function updateKit(string $name, string $armor, string $inventory, string $newName, ) : Generator {
		$this->conn->executeChange("properduels.update.kit", ["name" => $name, "armor" => $armor, "inventory" => $inventory, "newName" => $newName, ], yield Await::RESOLVE, yield Await::REJECT);
		return yield Await::ONCE;
	}
}